import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
export const metadata: Metadata = {
  // This is the title that shows up in the browser tab
  title: "Ashish AI | My Digital Twin",

  // This is the main description for search engines
  description: "A conversational AI, powered by Gemini and personalized by Ashish Mishra. Ask me anything about my projects, skills, and experience.",

  // This is for social media previews (Facebook, LinkedIn, etc.)
  openGraph: {
    title: "Ashish AI: A Conversation with my Digital Twin",
    description: "Ask me anything about my projects, skills, and experience.",
    url: "https://ashish-ai.vercel.app/", // <-- IMPORTANT: Replace with your actual Vercel URL
    siteName: "Ashish AI",
    images: [
      {
        url: "/og-image.png", // <-- This points to the image you put in the 'public' folder
        width: 1200,
        height: 630,
      },
    ],
    locale: "en_US",
    type: "website",
  },

  // This is for Twitter previews
  twitter: {
    card: "summary_large_image",
    title: "Ashish AI: A Conversation with my Digital Twin",
    description: "Ask me anything about my projects, skills, and experience.",
    images: ["/og-image.png"], // <-- This also points to your image
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
